### ISSUE TITLE
Add relevant ipv4 prefixes from IANA IPv4 Special-Purpose Address Registry to bogon filter

### ISSUE THREAD

**Issue by multichill** [NLNOG/bgpfilterguide#13]
https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml contains a lot of prefixes that should never be seen in the global BGP routing table. These should be filtered out.

**Comment by job** [comment]
Isn't this covered in http://bgpfilterguide.nlnog.net/guides/bogon_prefixes/ ? - or are we missing prefixes, if so please consider submitting a PR! :)
