### ISSUE TITLE
RFC7526 2002::/16

### ISSUE THREAD

**Issue by momorientes** [NLNOG/bgpfilterguide#62]
Hi All,

in the `bogon_prefixes` guide `2002::/16` is considered a bogon with remarks towards RFC7526, however [Section 4 of the RFC]( https://tools.ietf.org/html/rfc7526#section-4) clearly states that this does not deprecate 2002::/16:
```
   The basic unicast 6to4 mechanism defined in [RFC3056] and the
   associated 6to4 IPv6 prefix 2002::/16 are not deprecated.  
```

By looking at our Tier1 Transits we see 2002::/16 from Telia but not from NTT, which makes sense since @job announced NTTs removal in the [RIPE routing WG](https://www.ripe.net/ripe/mail/archives/routing-wg/2018-June/003574.html).

I couldn't find any official deprecation of 2002::/16 and the remarks to RFC7526 in the filter guide seem to be misleading.

Is there any document deprecating 2002::/16? I do not have any personal opinion on this prefix or 6to4 in general, however we are receiving customer complaints due to our implementation of the filter guide .

**Comment by job** [comment]
What is the customer complaint? What breaks? Why are they using still on public 6to4 gateways? :)

The transition mechanism itself is deprecated (as per RFC 7526)

It is not clear to me why the prefix was not deprecated along with the mechanism, perhaps they thought some transition period was needed. We're now 6 years later, someone could write an internet-draft to start the IETF process to deprecate this more heavily, but that's additional paperwork I'm not willing to pursue myself.

**Comment by momorientes** [comment]
I'll try to get more information out of the customer, for now we only have the complaint that this isn't working and upon tracing I ended up here.

**Comment by momorientes** [comment]
We never heard back from the customer, I guess we can close this issue. At least now there's a point of reference on why 2002::/16 is rejected in the guide even if it's formally not part of RFC7526.
Thanks for your clarification @job.
